// Static question bank used by the free Diagnostico de Lacunas tool.
// Kept intentionally small (3 areas x 3 questions per exam) so the quiz
// stays fast; the goal is to estimate strengths/gaps, not to be exhaustive.
import type { QuizQuestion } from './scoring';

export const QUESTIONS: QuizQuestion[] = [
  // ---------------------------------------------------------------- ENEM
  { id: 'enem_ling_01', exam: 'enem', area: 'linguagens', difficulty: 'facil',
    question: 'Em um texto dissertativo-argumentativo, qual e a funcao principal da tese?',
    options: ['Narrar um fato do cotidiano', 'Apresentar o ponto de vista que sera defendido', 'Listar fontes bibliograficas', 'Descrever um cenario'],
    correctOption: 1, explanationHint: 'A tese e a ideia central que o autor vai defender ao longo do texto.' },
  { id: 'enem_ling_02', exam: 'enem', area: 'linguagens', difficulty: 'medio',
    question: 'O uso de figuras de linguagem como a metafora tem como principal efeito:',
    options: ['Tornar o texto mais objetivo', 'Criar sentidos por meio de comparacoes implicitas', 'Eliminar a ambiguidade', 'Seguir a norma culta rigidamente'],
    correctOption: 1, explanationHint: 'A metafora aproxima sentidos diferentes sem usar conectivos comparativos.' },
  { id: 'enem_ling_03', exam: 'enem', area: 'linguagens', difficulty: 'dificil',
    question: 'Em textos publicitarios, a intertextualidade e usada principalmente para:',
    options: ['Copiar outro texto integralmente', 'Dialogar com um repertorio conhecido do leitor para gerar efeito de sentido', 'Evitar qualquer referencia cultural', 'Reduzir o texto a poucas palavras'],
    correctOption: 1, explanationHint: 'A intertextualidade ativa conhecimentos previos do leitor para reforcar a mensagem.' },
  { id: 'enem_mat_01', exam: 'enem', area: 'matematica', difficulty: 'facil',
    question: 'Se um produto custava R$ 80 e teve aumento de 15%, qual o novo preco?',
    options: ['R$ 88', 'R$ 92', 'R$ 95', 'R$ 100'],
    correctOption: 1, explanationHint: '80 + 15% de 80 = 80 + 12 = 92.' },
  { id: 'enem_mat_02', exam: 'enem', area: 'matematica', difficulty: 'medio',
    question: 'Qual e a area de um retangulo com lados 7 cm e 4 cm?',
    options: ['11 cm2', '22 cm2', '28 cm2', '32 cm2'],
    correctOption: 2, explanationHint: 'Area do retangulo = base x altura = 7 x 4 = 28.' },
  { id: 'enem_mat_03', exam: 'enem', area: 'matematica', difficulty: 'dificil',
    question: 'Em uma progressao aritmetica de razao 3, se o primeiro termo e 2, qual e o 10 termo?',
    options: ['27', '29', '30', '32'],
    correctOption: 1, explanationHint: 'a10 = a1 + (n-1) x r = 2 + 9 x 3 = 29.' },
  { id: 'enem_cn_01', exam: 'enem', area: 'ciencias_natureza', difficulty: 'facil',
    question: 'Qual processo e responsavel pela producao de oxigenio pelas plantas?',
    options: ['Respiracao celular', 'Fotossintese', 'Fermentacao', 'Osmose'],
    correctOption: 1, explanationHint: 'A fotossintese converte gas carbonico e agua em glicose e oxigenio.' },
  { id: 'enem_cn_02', exam: 'enem', area: 'ciencias_natureza', difficulty: 'medio',
    question: 'A Lei de Newton que explica "acao e reacao" e a:',
    options: ['Primeira Lei', 'Segunda Lei', 'Terceira Lei', 'Lei da Gravitacao'],
    correctOption: 2, explanationHint: 'A Terceira Lei de Newton trata do par acao-reacao entre corpos.' },
  { id: 'enem_cn_03', exam: 'enem', area: 'ciencias_natureza', difficulty: 'dificil',
    question: 'Em uma reacao de combustao completa de hidrocarbonetos, os produtos formados sao:',
    options: ['Apenas agua', 'Gas carbonico e agua', 'Apenas gas carbonico', 'Oxigenio e nitrogenio'],
    correctOption: 1, explanationHint: 'A combustao completa de hidrocarbonetos gera CO2 e H2O.' },

  // ----------------------------------------------------------------- OAB
  { id: 'oab_const_01', exam: 'oab', area: 'constitucional', difficulty: 'facil',
    question: 'A Constituicao Federal de 1988 classifica o Brasil como:',
    options: ['Estado unitario', 'Republica Federativa', 'Monarquia parlamentarista', 'Confederacao'],
    correctOption: 1, explanationHint: 'O Art. 1 da CF/88 define o Brasil como Republica Federativa.' },
  { id: 'oab_const_02', exam: 'oab', area: 'constitucional', difficulty: 'medio',
    question: 'Sao poderes da Uniao, independentes e harmonicos entre si:',
    options: ['Executivo e Legislativo apenas', 'Legislativo, Executivo e Judiciario', 'Apenas o Judiciario', 'Executivo e Ministerio Publico'],
    correctOption: 1, explanationHint: 'Art. 2 da CF/88 estabelece a triparticao de poderes.' },
  { id: 'oab_const_03', exam: 'oab', area: 'constitucional', difficulty: 'dificil',
    question: 'O remedio constitucional usado para proteger direito liquido e certo nao amparado por habeas corpus e habeas data e:',
    options: ['Mandado de seguranca', 'Acao popular', 'Mandado de injuncao', 'Habeas corpus'],
    correctOption: 0, explanationHint: 'O mandado de seguranca (Art. 5, LXIX) protege direito liquido e certo.' },
  { id: 'oab_civil_01', exam: 'oab', area: 'civil', difficulty: 'facil',
    question: 'A capacidade civil plena, em regra, e adquirida aos:',
    options: ['16 anos', '18 anos', '21 anos', '25 anos'],
    correctOption: 1, explanationHint: 'O Codigo Civil fixa a maioridade civil aos 18 anos.' },
  { id: 'oab_civil_02', exam: 'oab', area: 'civil', difficulty: 'medio',
    question: 'No contrato de compra e venda, a obrigacao do vendedor e principalmente:',
    options: ['Pagar o preco', 'Entregar a coisa vendida', 'Registrar o contrato', 'Fiscalizar o comprador'],
    correctOption: 1, explanationHint: 'Ao vendedor cabe entregar a coisa; ao comprador, pagar o preco.' },
  { id: 'oab_civil_03', exam: 'oab', area: 'civil', difficulty: 'dificil',
    question: 'A responsabilidade civil objetiva se caracteriza por:',
    options: ['Exigir prova de culpa do agente', 'Dispensar a prova de culpa, bastando o nexo causal e o dano', 'Nao gerar dever de indenizar', 'Aplicar-se apenas a contratos'],
    correctOption: 1, explanationHint: 'Na responsabilidade objetiva, a culpa e dispensada; basta nexo e dano.' },
  { id: 'oab_penal_01', exam: 'oab', area: 'penal', difficulty: 'facil',
    question: 'O principio penal segundo o qual nao ha crime sem lei anterior que o defina e chamado de:',
    options: ['Principio da insignificancia', 'Principio da legalidade', 'Principio da culpabilidade', 'Principio da adequacao social'],
    correctOption: 1, explanationHint: 'Nullum crimen sine lege e o principio da legalidade/reserva legal.' },
  { id: 'oab_penal_02', exam: 'oab', area: 'penal', difficulty: 'medio',
    question: 'Um crime consumado, mas cujo resultado nao ocorreu por circunstancias alheias a vontade do agente, e classificado como:',
    options: ['Crime impossivel', 'Tentativa', 'Crime continuado', 'Concurso de crimes'],
    correctOption: 1, explanationHint: 'A tentativa ocorre quando o crime nao se consuma por motivos externos a vontade do agente.' },
  { id: 'oab_penal_03', exam: 'oab', area: 'penal', difficulty: 'dificil',
    question: 'A excludente de ilicitude aplicavel quando alguem age para repelir injusta agressao, atual ou iminente, e:',
    options: ['Estado de necessidade', 'Legitima defesa', 'Estrito cumprimento do dever legal', 'Exercicio regular de direito'],
    correctOption: 1, explanationHint: 'A legitima defesa exige agressao injusta, atual ou iminente, e reacao proporcional.' },

  // ----------------------------------------------------------------- CPA
  { id: 'cpa_mercado_01', exam: 'cpa', area: 'mercado_financeiro', difficulty: 'facil',
    question: 'A instituicao responsavel por regular e fiscalizar o mercado de capitais no Brasil e a:',
    options: ['CVM', 'ANBIMA', 'FEBRABAN', 'Banco do Brasil'],
    correctOption: 0, explanationHint: 'A CVM (Comissao de Valores Mobiliarios) regula o mercado de capitais.' },
  { id: 'cpa_mercado_02', exam: 'cpa', area: 'mercado_financeiro', difficulty: 'medio',
    question: 'O orgao normativo maximo do Sistema Financeiro Nacional e o:',
    options: ['Banco Central', 'CVM', 'CMN (Conselho Monetario Nacional)', 'Tesouro Nacional'],
    correctOption: 2, explanationHint: 'O CMN define as diretrizes gerais da politica monetaria e financeira.' },
  { id: 'cpa_mercado_03', exam: 'cpa', area: 'mercado_financeiro', difficulty: 'dificil',
    question: 'O compulsorio bancario e um instrumento de politica monetaria que:',
    options: ['Aumenta sempre a inflacao', 'Recolhe parte dos depositos dos bancos ao Banco Central', 'E opcional para os bancos', 'Se aplica apenas a fundos imobiliarios'],
    correctOption: 1, explanationHint: 'O compulsorio retem parte dos depositos captados, controlando a liquidez do sistema.' },
  { id: 'cpa_invest_01', exam: 'cpa', area: 'investimentos', difficulty: 'facil',
    question: 'Um fundo de investimento em renda fixa aplica principalmente em:',
    options: ['Acoes de empresas', 'Titulos publicos e privados de renda fixa', 'Imoveis fisicos', 'Moedas estrangeiras apenas'],
    correctOption: 1, explanationHint: 'Fundos de renda fixa concentram a carteira em titulos de divida.' },
  { id: 'cpa_invest_02', exam: 'cpa', area: 'investimentos', difficulty: 'medio',
    question: 'A marcacao a mercado de um titulo tem como objetivo:',
    options: ['Fixar o preco de compra para sempre', 'Refletir o valor atual do ativo conforme condicoes de mercado', 'Eliminar o risco de credito', 'Garantir rentabilidade minima'],
    correctOption: 1, explanationHint: 'A marcacao a mercado atualiza o preco do ativo pelo valor justo de mercado.' },
  { id: 'cpa_invest_03', exam: 'cpa', area: 'investimentos', difficulty: 'dificil',
    question: 'O risco de um fundo nao conseguir vender um ativo rapidamente sem perda significativa de valor e chamado de:',
    options: ['Risco de credito', 'Risco de mercado', 'Risco de liquidez', 'Risco operacional'],
    correctOption: 2, explanationHint: 'O risco de liquidez esta ligado a dificuldade de conversao do ativo em caixa sem perdas.' },
  { id: 'cpa_etica_01', exam: 'cpa', area: 'etica', difficulty: 'facil',
    question: 'O Codigo de Distribuicao da ANBIMA tem como principal objetivo:',
    options: ['Definir aliquotas de imposto de renda', 'Estabelecer regras de conduta na distribuicao de produtos de investimento', 'Regular o mercado imobiliario', 'Fiscalizar bancos centrais estrangeiros'],
    correctOption: 1, explanationHint: 'O codigo trata de praticas equitativas na oferta e distribuicao de produtos.' },
  { id: 'cpa_etica_02', exam: 'cpa', area: 'etica', difficulty: 'medio',
    question: 'O principio do "suitability" na distribuicao de investimentos exige que o produto ofertado seja:',
    options: ['O mais rentavel do mercado', 'Adequado ao perfil e objetivos do investidor', 'Sempre de renda fixa', 'Isento de qualquer risco'],
    correctOption: 1, explanationHint: 'Suitability significa adequar o produto ao perfil de risco do cliente.' },
  { id: 'cpa_etica_03', exam: 'cpa', area: 'etica', difficulty: 'dificil',
    question: 'Um conflito de interesse na distribuicao de fundos ocorre quando:',
    options: ['O cliente le o regulamento do fundo', 'O distribuidor recebe incentivo para indicar um produto que nao e o mais adequado ao cliente', 'O fundo tem taxa de administracao divulgada', 'O gestor segue a politica de investimento do fundo'],
    correctOption: 1, explanationHint: 'Conflito de interesse surge quando o incentivo do distribuidor diverge do melhor interesse do cliente.' },

  // ------------------------------------------------------------- CONCURSO
  { id: 'conc_port_01', exam: 'concurso', area: 'portugues', difficulty: 'facil',
    question: 'Na frase "Os candidatos, que estudaram bastante, foram aprovados", a oracao entre virgulas e:',
    options: ['Restritiva', 'Explicativa', 'Coordenada', 'Reduzida de infinitivo'],
    correctOption: 1, explanationHint: 'Orcoes explicativas vem entre virgulas e acrescentam informacao adicional.' },
  { id: 'conc_port_02', exam: 'concurso', area: 'portugues', difficulty: 'medio',
    question: 'A crase e obrigatoria em qual construcao?',
    options: ['Vou a pe', 'Cheguei a casa', 'Refiro-me a proposta apresentada', 'Estava a beira do rio'],
    correctOption: 2, explanationHint: 'Antes de palavra feminina determinada regida por verbo que pede a preposicao "a", usa-se crase.' },
  { id: 'conc_port_03', exam: 'concurso', area: 'portugues', difficulty: 'dificil',
    question: 'O emprego do "se" como particula apassivadora ocorre em:',
    options: ['Precisa-se de funcionarios', 'Vendem-se casas', 'Trabalha-se muito aqui', 'Ele se machucou'],
    correctOption: 1, explanationHint: '"Vendem-se casas" tem sujeito paciente (casas), configurando voz passiva sintetica.' },
  { id: 'conc_rlm_01', exam: 'concurso', area: 'raciocinio_logico', difficulty: 'facil',
    question: 'Se todo A e B, e todo B e C, entao pode-se concluir que:',
    options: ['Todo C e A', 'Todo A e C', 'Nenhum A e C', 'Nada pode ser concluido'],
    correctOption: 1, explanationHint: 'Por transitividade logica, se A esta contido em B e B em C, entao A esta contido em C.' },
  { id: 'conc_rlm_02', exam: 'concurso', area: 'raciocinio_logico', difficulty: 'medio',
    question: 'A negacao da proposicao "Todos os candidatos passaram" e:',
    options: ['Nenhum candidato passou', 'Pelo menos um candidato nao passou', 'Todos os candidatos nao passaram', 'Alguns candidatos passaram'],
    correctOption: 1, explanationHint: 'A negacao de "todos" e "existe pelo menos um que nao".' },
  { id: 'conc_rlm_03', exam: 'concurso', area: 'raciocinio_logico', difficulty: 'dificil',
    question: 'Em uma sequencia 2, 6, 12, 20, 30, o proximo numero e:',
    options: ['36', '40', '42', '44'],
    correctOption: 2, explanationHint: 'As diferencas aumentam em 2 a cada termo (4,6,8,10,12); 30 + 12 = 42.' },
  { id: 'conc_dir_01', exam: 'concurso', area: 'direito_administrativo', difficulty: 'facil',
    question: 'O principio que exige que a Administracao Publica siga estritamente o que a lei determina e o principio da:',
    options: ['Eficiencia', 'Legalidade', 'Publicidade', 'Moralidade'],
    correctOption: 1, explanationHint: 'Pelo principio da legalidade, o administrador so pode agir conforme autorizado em lei.' },
  { id: 'conc_dir_02', exam: 'concurso', area: 'direito_administrativo', difficulty: 'medio',
    question: 'O ato administrativo pelo qual a Administracao retira um ato ilegal e chamado de:',
    options: ['Revogacao', 'Anulacao', 'Convalidacao', 'Homologacao'],
    correctOption: 1, explanationHint: 'A anulacao retira atos ilegais; a revogacao retira atos legais mas inconvenientes.' },
  { id: 'conc_dir_03', exam: 'concurso', area: 'direito_administrativo', difficulty: 'dificil',
    question: 'A licitacao pode ser dispensada de acordo com a lei quando, por exemplo, ha:',
    options: ['Qualquer valor de contrato', 'Situacao de guerra ou emergencia devidamente caracterizada', 'Preferencia pessoal do gestor', 'Interesse de uma unica empresa em participar'],
    correctOption: 1, explanationHint: 'A lei de licitacoes preve hipoteses taxativas de dispensa, como guerra ou emergencia.' },
];

export function getQuestionsForExam(exam: string): QuizQuestion[] {
  return QUESTIONS.filter((q) => q.exam === exam);
}
